### ISSUE TITLE
Stylistic and aesthetic adjustments

### ISSUE THREAD

**Issue by curran** [cfinst/cfinst.github.io#13]
Colors, fonts, layouts and finishing touches.

**Note:** This issue is directly from the Statement of Work, and may need to be broken up into smaller issues.

**Comment by curran** [comment]
I think this can be closed. @seemantk Your thoughts?

**Comment by seemantk** [comment]
This is a bit of a vague ticket, so I support closing it on that front, alone.
Having said that, let's make sure on the call this week  that Michael, @bglavin and Ronda are happy with the look and feel (colors/fonts/layouts).

One question that does come up in my mind is about the layout's responsiveness. That is to say, when the viewport gets smaller, does the viz still make sense when it's all in one column?

**Comment by curran** [comment]
@seemantk Indeed. I think that's a great approach. Closing, but let's bring it up on the call.
