### ISSUE TITLE
Format legend items using commas

### ISSUE THREAD

**Issue by curran** [cfinst/cfinst.github.io#153]
Minor thing, but something that I think we can address fairly easily.

![image](https://cloud.githubusercontent.com/assets/68416/23295028/6ff607ca-fa94-11e6-967e-483d4dc0c62f.png)

We're using a comma in "$10,000 or Greater", but not in the intervals, like "$2501 - $5000".

It would be great to unify these, and see things like "$2,501 - $5,000" with the commas.

**Comment by curran** [comment]
Just realized that the way we are generating the legends using Jekyll is posing a barrier to implementing this formatting logic with D3 https://github.com/cfinst/cfinst.github.io/blob/db0dd75caeaf53c353f6e508c7d8881e7bb5e041/_includes/legend.html

```js

{% for legendtype in section[1].legends %}
  {% for legend in legendtype[1] %}
  <ul class="list-unstyled legend-{{ legend[0] }}">
  {% for item in legend[1] %}
    <li>
      <svg role="presentation" fill="{{ item.color }}">
        <use xlink:href="#cell">
      </svg>
      <span>{% if item.label %}{{ item.label }}{% else %}${{ item.min }} - ${{ item.max }}{% endif %}</span>
    </li>
  {% endfor %}
  </ul>
  {% endfor %}
{% endfor %}
```

Maybe one approach would be to set the `value` or `data-value` attributes in the legend DOM, then go back over the elements using D3, formatting those values into the `.text()` of the element using d3-format?

**Comment by seemantk** [comment]
hi @curran!  So, here's the thing.  We don't actually need to build the legends as in the above code. We can use d3 and enter/update/exit to create one changing legend (as we had before).  And we can still let it live in Jekyll for non-developer configuration.

This is where we [generate colorScale via Jekyll](https://github.com/cfinst/cfinst.github.io/blob/master/js/schematic.js#L292-L309).  Thanks to your opening this ticket, I see that this is duplicate code.  The colorScale's domain() and range() should be exactly what we need to create the legends dynamically.

**Comment by curran** [comment]
@seemantk That's a great idea! I'm happy to hear this direction, sounds sensible to me to have the data follow "one path" from Jekyll into JS, via that color scale definition, then percolate through (via D3) to the legend. We can totally keep the same DOM structure of the legend.

**Comment by seemantk** [comment]
@curran, please see #174 -- I've simplified things a bit there.  Just one legend <ul> which gets changed.  The active tab stuff is much smaller, etc.

**Comment by curran** [comment]
Great, having a look. Is it still WIP?

**Comment by seemantk** [comment]
I've just made the last commits to it (to fix the visible data download error).  It's now all yours for the number formatting and whatever other optimizations and improvements you'd like to make :)

**Comment by curran** [comment]
Great. Thanks! Looks like nice changes so far.

**Comment by curran** [comment]
After 
![image](https://cloud.githubusercontent.com/assets/68416/24251919/c7e1b52e-1001-11e7-91f2-d7946845f0ed.png)
