### ISSUE TITLE
Map hover lost on small display

### ISSUE THREAD

**Issue by curran** [cfinst/cfinst.github.io#162]
When I resize the browser to simulate a tablet, the hover interaction on the map is gone.

![image](https://cloud.githubusercontent.com/assets/68416/23459233/75c7d808-fea5-11e6-858c-e7cf281e9486.png)

**Comment by seemantk** [comment]
@curran are you still experiencing this issue?

**Comment by curran** [comment]
Yes, just tested with the latest in https://github.com/cfinst/cfinst.github.io/pull/174#pullrequestreview-28303532

More details for reproduction:

 * Using Chrome in Linux
 * Resize the window horizontally to make the breakpoints adjust the layout (as in screenshot)
 * Hover interaction on state shapes is gone.

**Comment by seemantk** [comment]
How strange!  At that exact breakpoint, the div that contains "grid" is basically sitting on top of everything.  It's not just the atlas that isn't hover responsive: even the dropdowns are blocked.  Only grid interactions work here at that breakpoint.
