### ISSUE TITLE
Year not bold after clicking on grid axis

### ISSUE THREAD

**Issue by curran** [cfinst/cfinst.github.io#176]
Most likely this is a string -> number parsing issue and easily fixed.

Maybe better to just defensively parse downstream, reversing https://github.com/cfinst/cfinst.github.io/commit/cab7acf0a8acc2fc216fbe154da15a8427726c50 . That way we'll ALWAYS guarantee that the selected year is bolded, even if it was not parsed before dispatch.

**Comment by seemantk** [comment]
Yes, probably best, actually.
