### ISSUE TITLE
Define Tie-breaking Scheme for Ordinal Scales

### ISSUE THREAD

**Issue by seemantk** [cfinst/cfinst.github.io#183]
Scales without numeric values will have an undefined sort when done "By Value"
I suggest we disable the "By Value" sort.

We can either:
- force "Alphabetical"; or
- use whatever order was already left there

**Comment by curran** [comment]
@seemantk The sorting is currently defined as alphanumeric, with respect to the values.

The tie breaking behavior is undefined though, that can be addressed.

**Comment by seemantk** [comment]
@curran ah yes, makes sense!  
+1 to your suggestion

**Comment by curran** [comment]
@seemantk Haha sure enough, we were sorting on these "sum" values for ordinal scales:

```
YesYesYesYesYesYesYesYesYes
7grid.js:245 0NoNoNoNoNoNoNoNoNo
grid.js:245 0YesNoNoNoNoNoNoNoNo
3grid.js:245 0NoNoNoNoNoNoNoNoNo
3grid.js:245 0YesYesYesYesYesYesYesYesYes
10grid.js:245 0NoNoNoNoNoNoNoNoNo
grid.js:245 0YesYesYesYesYesYesYesYesYes
grid.js:245 0NoNoNoNoNoNoNoNoNo
grid.js:245 0YesYesYesYesYesYesYesYesYes
6grid.js:245 0NoNoNoNoNoNoNoNoNo
grid.js:245 0NoNoNoNoNoYesYesYesNo
3grid.js:245 0NoNoNoNoNoNoNoNoNo
2grid.js:245 0YesYesYesYesYesYesYesYesYes
grid.js:245 0NoNoNoNoNoNoNoNoNo
grid.js:245 0YesYesYesYesYesYesYesYesYes
2grid.js:245 0NoNoNoNoNoNoNoNoNo
```

**Comment by curran** [comment]
As zany as it might seem, sorting on these "sum" values actually does give us a well-behaved tie breaking behavior.

As an example, consider this case:

![image](https://cloud.githubusercontent.com/assets/68416/24599863/c8dd28de-186f-11e7-8205-4c4bf7e13b13.png)

Here are the tie breaker values for the area circled in red:

```
AK: 0Missing DataNoNoNoNoNoNoYesYesYes
grid.js:277 IA: 0NoInoperative mid-cycleNoMissing DataYesYesYesYesYesYes
grid.js:277 UT: 0NoNoNoNoNoNoNoNoYesYes
grid.js:277 IL: 0NoNoNoNoNoNoNoYesYesYes
grid.js:277 SD: 0NoNoNoNoNoNoYesYesYesYes
grid.js:277 VA: 0NoNoNoNoNoYesYesYesYesYes
grid.js:277 AZ: 0YesYesYesYesYesYesYesYesYesYes
grid.js:277 DE: 0YesYesYesYesYesYesYesYesYesYes
```

The concatenation order here is from most recent year to least recent, so the effect here is a nice sorting that breaks ties on ordinal values giving precendence to more recent years.

This is the [branch with the debugging statement](https://github.com/cfinst/cfinst.github.io/pull/198/files), in case you want to have a closer look.

@seemantk I'm closing this issue as I feel this behavior is reasonable. Please feel free to reopen if you'd like to see a different solution.
