### ISSUE TITLE
Color bug

### ISSUE THREAD

**Issue by curran** [cfinst/cfinst.github.io#184]
I believe this may be a coloring bug?

![image](https://cloud.githubusercontent.com/assets/68416/24256218/903e5cc4-100d-11e7-9328-a93c52770a3c.png)

Should be pink, right? Maybe we have a threshold that's not big enough somewhere.

**Comment by seemantk** [comment]
Nice find!  is it a threshold or a comma-parsing bug, I wonder?

**Comment by curran** [comment]
After the fix in #197:

![image](https://cloud.githubusercontent.com/assets/68416/24599386/9f5f4f02-186d-11e7-9798-526d335fb72a.png)
