### ISSUE TITLE
Include titles in MD files in download package

### ISSUE THREAD

**Issue by curran** [cfinst/cfinst.github.io#188]
The `about.md` and `howto.md` files in the download .zip package to not have titles.

One easy way to do this would be to add it to the markdown, and remove the bit of JS that renders the heading (I think this is how we do it... will need to take a look).

**Comment by seemantk** [comment]
@curran this is a great idea.  Everything between the '---''s in those files is a variable that Jekyll uses to convert markdown to HTML.

I reckon we can parse out the title from bash, using something like:

`awk -F: '/title: / { print $2 }' _modals/contribution-limits/about.md 
`

**Comment by curran** [comment]
@seemantk That would be really cool! So maybe we could have one command in the package script that outputs

```
# Some Title
```

Then the next bit can append more lines onto there.

**Comment by seemantk** [comment]
I just sent you #190

**Comment by curran** [comment]
Closed in **Add Titles into the about & howto pages** #190
