### ISSUE TITLE
'tree' command is optional

### ISSUE THREAD

**Issue by seemantk** [cfinst/cfinst.github.io#189]
@curran the package-download script uses `tree` command, which is non-existent on standard Linux system.  Is it an alias on your system?

**Comment by seemantk** [comment]
Replaced the optional `tree` command with standard tooling (find and sed) in 414e4b3a863cb4666c785679d8a69ff8f2989a76

**Comment by curran** [comment]
@seemantk Ah yes, sorry about that. It can be safely removed, it was just to print out the directory structure.

**Comment by curran** [comment]
Closed in **Add Titles into the about & howto pages** #190
