### ISSUE TITLE
Update CFI CMS Links

### ISSUE THREAD

**Issue by curran** [cfinst/cfinst.github.io#192]
In the page http://cfinst.org/State/LawsDatabase.aspx

 * Visualization link should point to https://cfinst.github.io/
 * Download link should point either to http://cfinst.org/State/LawsDatabase_Download.aspx or https://cfinst.github.io/downloads/cfi-laws-database.zip

**Comment by seemantk** [comment]
closed by #199

**Comment by curran** [comment]
Reopening, as this is more about updating the links within the CMS page http://cfinst.org/State/LawsDatabase.aspx, which still needs to be done by @bglavin .

**Comment by curran** [comment]
@bglavin Just a note that this still is pending.

**Comment by bglavin** [comment]
Links are updated.
