### ISSUE TITLE
Phase II of Legend Highlighting

### ISSUE THREAD

**Issue by curran** [cfinst/cfinst.github.io#209]
Needs to be less jarring to the eyes.

Similar possibly to http://judicialselectionmap.brennancenter.org/?court=Supreme

![image](https://cloud.githubusercontent.com/assets/68416/24762037/c4cba264-1b0a-11e7-9220-f611937b5525.png)

![image](https://cloud.githubusercontent.com/assets/68416/24762051/cf706858-1b0a-11e7-93d5-f5e74bc7d12e.png)

Also possibly similar to https://bl.ocks.org/curran/0d2cc6698cad72a48027b8de0ebb417d

**Comment by seemantk** [comment]
The changes look much better @curran.  The red looks bright regardless.  I wonder if using a scale like this would help:

https://bl.ocks.org/mbostock/debaad4fcce9bcee14cf

**Comment by curran** [comment]
We have some new changes from #214 that implement this, but there is a problem remaining with light values:

![image](https://cloud.githubusercontent.com/assets/68416/24860274/74439900-1e11-11e7-8f91-029b66618cab.png)

In the above image, the circled area should show a highlighted value, but since the color of the highlighted value is light, it doesn't come through.

Possible solutions:

 * Use a gray overlay rather than white
 * Use a dark stroke around highlighted elements
 * Use a dark shadow around highlighted elements

**Comment by curran** [comment]
Here's what gray would look like

![image](https://cloud.githubusercontent.com/assets/68416/24860398/0aa27fba-1e12-11e7-858c-83310b6872ad.png)

**Comment by curran** [comment]
Aha! What if we set a dark stroke *only* if the highlighted elements are light colored? If only there were a way to compute "how light" is a given fill color, then we could use a stroke with the "opposite" darkness. Dark fill colors don't need the stroke at all, but the lighter ones do, proportionally to their lightness.
