### ISSUE TITLE
Make grid fully visible on load

### ISSUE THREAD

**Issue by curran** [cfinst/cfinst.github.io#255]
Several factors we can try:

 * try moving the interface elements from below the map over to below the elements on the right.
 * try changing the bounding box of the map
 * try adding margins on the left/right (not ideal, as we lose screen real estate)

**Comment by curran** [comment]
Closed by #258

**Comment by curran** [comment]
Reopened, as this is still an issue on Michael's display (cuts off after 2002).

Idea: use the current height of the browser to determing a left-right margin that shrinks the view such that the grid is fully visible.

Possibly useful: [Responding to Resize](https://bl.ocks.org/curran/3a68b0c81991e2e94b19)

**Comment by seemantk** [comment]
With regards to layout.  Here's the implication of the current layout from the perspective of a newbie without much context on what they're seeing

- tabs and page logo
  - crucial for navigation
- map
  - top left item, usually the first place people will look.
  - pros:
     - intriguing colors (esp. the popping blues of Contribution Limits)
  - cons:
     - map has no context, so the eyes will quickly scan and go to the right for context.
     - cost: microseconds of initial attention (when curiosity is at its peak for a newcomer)
- Question and Description (crucial UI/UX)
     - pros:
        - controls whatever is going on with the map.
     - cons:
        - still no context for a newcomer
        - cost: milliseconds of now waning attention
        - risk: frustration at not "getting it"
- Legend (crucial UI to explain the colors)
    - pros:
       - at least the colors now mean something
    - cons:
      - still no context for a newcomer
- Buttons
   - About this Topic
     - pros:
       - Context!
     - cons:
       - "Wait, what topic? Um....oh, Contribution Limits"
       - Cost:
          - Additional milliseconds of time/attention
          - Effort
   - Using this Page
     - pros:
       - Context!
     - cons:
       - I had to be patient to get to this one
   - Download Visible Data
       - Huh?
   - More Download Options
       - More huh?

**Comment by seemantk** [comment]
So, with regards to my previous comment, I think it would do us well to converge on some questions like:

- who is this page for?
- are we giving them what they need when they need it?
   - what are the more important things we need to tell a user
   - what are the most important things someone needs to know when they come in via:
      - web search on:
          - the topic of the viz
          - visualizations
          - @curran or @seemantk's visualizations
          - any of CFI people (rather than CFI things)
          - phrases within the topic
          - 2nd and 3rd order web searches on the topic
      - curiosity due to the press around this
      - experts, journalists and students who visit consciously
      - returning visitors

**Comment by curran** [comment]
@seemantk Great thoughts here. How can these translate into actions, such that we make improvements where we can, but don't disrupt the layout too much (I feel like it's fairly stable, and don't want to disturb the CFI team with major layout changes).

**Comment by curran** [comment]
Maybe one thing we could do is make the "About this Topic" and "Using this Page" buttons a blue color (Bootstrap's "btn-primary" I believe), so they stand out more at first glance?

**Comment by seemantk** [comment]
@curran, great call out, here are possibilities:

- Fold "Download" into a [button dropdown](http://getbootstrap.com/components/#btn-dropdowns) with two options 
- Put an [info icon](http://fontawesome.io/icon/info-circle/) button on the active tab.  (Contribution Limits (i)) which leads to "about this page"
- Put a [queston icon](http://fontawesome.io/icon/question-circle/) above the first drop down (top left or top right corner of that box) which leads to "how to use this page"

**Comment by curran** [comment]
Closing this issue, as we've concluded we cannot make the full grid appear on all display types.

Some of the ideas brought in this thread up may merit their own new issues though.
