### ISSUE TITLE
Intro Popup has bug with some Firefox users

### ISSUE THREAD

**Issue by seemantk** [cfinst/cfinst.github.io#274]
@curran, apologies as I'm still learning git/github-fu. I tried to just back out the PR, but I dunno it looks like it created a new PR.

Here's some info and resolution I found about the Firefox bug:
https://stackoverflow.com/questions/18877643/error-in-local-storage-ns-error-file-corrupted-firefox

**Comment by curran** [comment]
Thanks @seemantk for catching this bug, researching, and rolling back the change.

I wonder what the best direction would be here. The fact that you encountered this error gives me some overall hesitation about using `localStorage` altogether. We could achieve the same thing with Cookies, which it seems a more "tried and true" way, but from the snippets I've seen, dealing with cookies can be a bit tedious as compared to the `localStorage` API.

I do want to avoid errors like this at all cost, especially if it happens to the CFI folks and their audience, so I'm thinking to try my hand at a Cookies-based implementation.
