### ISSUE TITLE
Fix Sorting Issues

### ISSUE THREAD

**Issue by curran** [cfinst/cfinst.github.io#51]
Tie breakers at infinity are the main issue.

**Comment by curran** [comment]
@seemantk Yes, that's a great idea! I think we had something similar before with the "scorecard" concept, but it was confusing and I think it got removed at some point. We can re-create the logic from there, and use the Infinity & -Infinity occurrences as tie breakers.

Maybe the logic could be something like:

`var tieBreaker = count(Infinity, allYears) - count (-Infinity, allYears);`

where the Infinity occurrences have positive weight and the -Infinity occurrences have negative weight.

Having half a mind to close this as it's relatively minor, but if it's an easy addition it might be worth doing.

**Comment by seemantk** [comment]
In #178, I'm deferring back to alphabetical sort as the tie breakers for a couple of reasons:

- the transitions are more stable
- bonus: Michael prefers alphabetical sort

**Comment by curran** [comment]
I think I nailed this in #181.

Before:

![image](https://cloud.githubusercontent.com/assets/68416/24196247/0edc5450-0f23-11e7-95ef-21e521a1df95.png)

After:

![image](https://cloud.githubusercontent.com/assets/68416/24196272/26ae96ec-0f23-11e7-9611-e9cd86782d84.png)

**Comment by curran** [comment]
Though now that I see the inconsistent sorting on the left side and in the middle, I have a new idea - what if we break ties by *sum across all years*, where Infinities are given a weight of some large number, say 100,000?
